version: '3.8'
services:
  betana-front:
    container_name: betana-front
    image: node:slim
    working_dir: "/app"
    command: "npm start"
    volumes:
      - ./betana-front:/app
    ports:
      - "${PORT_FRONT}:3000"